server:
  port: 8080

spring:
  application:
    name: personal-expense-tracker


  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/expensetrackerdb
    username: root
    password: root
  jpa:
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true